[김태호] todo-list CRUD 구현
depromeet/todo-list-study pull request #4
Opened 2022-04-06 15:36 UTC by Ting-Kim

많이 부족하지만, 구현해봤습니다!
구현하면서 애매했던 부분은 _`// COMMENT:`_ 를 통해 달았습니다.
읽어주셔서 감사합니다 (__) 😊

2022-04-06 16:11 UTC, DongGeon0908 requested changes
고생하셨습니다!!!
제가 아는 부분에 대해서 review 남겼어요!!

저도 정확하게 todo-list 구현에 대한 답은 몰지만,
제가 드린 질문들에 대해 한번씩 고민해보시면 좋을 것 같아요!!

오늘도 극락코딩~

2022-04-06 16:11 UTC, DongGeon0908 commented on src/main/java/com/depromeet/todolist/todo/Todo.java
> +    }
접근제한자를 따로 선언하지 않은 이유가 있을까요?

2022-04-06 16:11 UTC, DongGeon0908 commented on src/main/java/com/depromeet/todolist/todo/Todo.java
> +    }
static 메서드로 만드신 이유가 궁금합니다!

2022-04-06 16:11 UTC, DongGeon0908 commented on src/main/java/com/depromeet/todolist/todo/TodoController.java
> +    }
롬복에서 생성자를 만들어주는 어노테이션이 있어용~

2022-04-06 16:11 UTC, DongGeon0908 commented on src/main/java/com/depromeet/todolist/todo/TodoService.java
> +    }
롬복에 있는 생성자 생성 어노테이션!!

2022-04-06 16:11 UTC, DongGeon0908 commented on src/main/java/com/depromeet/todolist/todo/TodoService.java
> +    public Optional<List<TodoResponse>> findAll() {
Optional하게 가져가는건 Service 내부에서 끝내야 합니다!

2022-04-06 16:11 UTC, DongGeon0908 commented on src/main/java/com/depromeet/todolist/todo/TodoService.java
> +    // COMMENT: @Transactional(readOnly = true)를 생략해도 되는지
선택인 것 같습니다!
저는 명시적으로 작성해요

2022-04-06 16:11 UTC, DongGeon0908 commented on src/main/java/com/depromeet/todolist/todo/TodoService.java
> +                });
좋네요!!

2022-04-06 16:11 UTC, DongGeon0908 commented on src/main/java/com/depromeet/todolist/todo/TodoService.java
> +        findById(todoId).update(todoRequest);
생성에서는 값을 꺼내서 생성자로 보냈는데, update 로직에서는 dto를 바로 보내고 있네요!!
어떤 방법이든 통일된 방법을 지향해주세용

2022-04-06 16:11 UTC, DongGeon0908 commented on src/main/java/com/depromeet/todolist/todo/TodoController.java
> +                        .orElseThrow(() -> new IllegalArgumentException()));
Throw를 던져주는게 Controller보다는 service에서 진행하는게 바람직합니다!
어차피 조회하는거 거기서 일괄 exception 던지는게 코드양도 줄어들겠죵

2022-04-06 16:11 UTC, DongGeon0908 commented on src/main/java/com/depromeet/todolist/todo/TodoController.java
> +                        .orElseThrow(() -> new IllegalArgumentException()));
위와 마찬가지입니당!

2022-04-06 16:11 UTC, DongGeon0908 commented on src/main/java/com/depromeet/todolist/todo/TodoController.java
> +    @PostMapping("/{todoId}")
저장 로직인데 todoId를 어떻게 얻을까요??

2022-04-06 16:11 UTC, DongGeon0908 commented on src/main/java/com/depromeet/todolist/todo/TodoController.java
> +@RestController(value = "/api/todos")
restful하다는게 무엇일까요?
기본적으로 우리가 직접 가능한 부분에 대해서는 이번 기회에 한번 적용해보시길 추천드려요

2022-04-06 16:11 UTC, DongGeon0908 commented on src/main/java/com/depromeet/todolist/common/dto/ApiResult.java
> +    }
그냥 getter 아닌가용??

2022-04-06 16:17 UTC, Ting-Kim commented on src/main/java/com/depromeet/todolist/todo/dto/TodoResponse.java
> +        return new TodoResponse(todo.getContent(), todo.getType());
public static, 감사합니다!
static으로 만든 이유는 사실 정적 생성메서드를 이용하면 이름을 가질 수 있기 때문에 좋다는 내용을 접해서 사용해봤습니다.
(정적 팩토리 메서드 관련 내용인데, 이건 싱글톤일 경우에만 적용되는걸까요 😅)

2022-04-06 16:18 UTC, Ting-Kim commented on src/main/java/com/depromeet/todolist/todo/dto/TodoRequest.java
> +    private TodoType type;
spring-validation을 생각했었는데, 뭔가 점진적으로 기능을 붙여나가는 형태로 하고 싶어서 먼저 PR을 드렸습니다 :)
추후 붙여보도록 하겠습니다 ㅎㅎ

2022-04-06 16:19 UTC, Ting-Kim commented on src/main/java/com/depromeet/todolist/common/dto/ApiError.java
> +    }
아, 기존에 lombok을 최대한 쓰지말라는 이야기를 어디선가 들어서 무의식적으로 그랬던 것 같아요. lombok 쓸거면 해당 기능을 쓰는게 좋겠죠?

2022-04-06 16:19 UTC, Ting-Kim commented on src/main/java/com/depromeet/todolist/common/dto/ApiError.java
> +    }
오 감사합니다!

2022-04-06 16:21 UTC, Ting-Kim commented on src/main/java/com/depromeet/todolist/common/dto/ApiResult.java
> +    private final boolean success;
아 그러네요. 이전에 진행했던 프로젝트에서 팀원이 `boolean`으로 받아볼 수있었으면 좋겠다는 의견 때문에 넣었는데 말씀해주신 내용이 맞는 것 같아요!

2022-04-06 16:24 UTC, Ting-Kim commented on src/main/java/com/depromeet/todolist/todo/TodoController.java
> +                        .orElseThrow(() -> new IllegalArgumentException()));
`OK/ERROR` 로 나뉘는게 아닌, 하나로 하고 `StatusCode`로 판단하면 된다는 의미이신게 맞나요?!

2022-04-06 16:25 UTC, Ting-Kim commented on src/main/java/com/depromeet/todolist/todo/TodoController.java
> +    @PostMapping("/{todoId}")
아앗,,,그러네요. 시정하겠습니다..!

2022-04-06 16:25 UTC, Ting-Kim commented on src/main/java/com/depromeet/todolist/todo/TodoController.java
> +        return ApiResult.OK(true);
오 참고하겠습니다! 😉

2022-04-06 16:26 UTC, Ting-Kim commented on src/main/java/com/depromeet/todolist/common/dto/ApiResult.java
> +    }
맞죠! 메서드명에서 의미가 느껴지면 좋겠다고 생각해서 바꾸긴 했습니다. 저런 경우는 그냥 `getter`가 나으려나요?

2022-04-06 16:28 UTC, Ting-Kim commented on src/main/java/com/depromeet/todolist/todo/TodoController.java
> +@RestController(value = "/api/todos")
이게 가장 어려운 말씀이네요.. 안그래도 좀 더 필요한 고민인 것 같습니다. 좀 찾아보고 인사이트를 넓혀 오겠습니다!

2022-04-06 16:29 UTC, Ting-Kim commented
동건님 바쁘신 와중에 리뷰 달아주셔서 너무 감사해요.
계속해서 고민해보고, 개선해보겠습니다!

2022-04-07 10:10 UTC, DongGeon0908 commented on src/main/java/com/depromeet/todolist/todo/dto/TodoResponse.java
> +        return new TodoResponse(todo.getContent(), todo.getType());
그리고 Response에서 여러 이름이 생겨나지는 않을 것 같아용

2022-04-07 10:10 UTC, DongGeon0908 commented on src/main/java/com/depromeet/todolist/todo/dto/TodoRequest.java
> +    private TodoType type;
넵넵!

2022-04-07 10:14 UTC, DongGeon0908 commented on src/main/java/com/depromeet/todolist/common/dto/ApiError.java
> +    }
흠.. 그러면, 롬복 라이브러리를 지우고 한번 진행해보시죠!!

2022-04-07 10:15 UTC, DongGeon0908 commented on src/main/java/com/depromeet/todolist/common/dto/ApiResult.java
> +    private final boolean success;
넵넵~~!

2022-04-07 10:16 UTC, DongGeon0908 commented on src/main/java/com/depromeet/todolist/todo/TodoController.java
> +                        .orElseThrow(() -> new IllegalArgumentException()));
아! Controller에서 exception을 던져주는 것 보다는 Service에서 모두 마무리 되어야 한다는 의미였습니다!

2022-04-07 10:16 UTC, DongGeon0908 commented on src/main/java/com/depromeet/todolist/todo/TodoController.java
> +    @PostMapping("/{todoId}")
ㅋㅋㅋㅋ

2022-04-07 10:17 UTC, DongGeon0908 commented on src/main/java/com/depromeet/todolist/common/dto/ApiResult.java
> +    }
isSuccess가 다른 곳에서도 쓰인다면 괜찮은디, 
그게 아니라면 굳이 메서드명을 별도로 지어주는게 좋은건지.. 저는 모르겠습니다!

2022-04-07 10:17 UTC, DongGeon0908 commented
화이팅입니다!

2022-04-07 14:02 UTC, Ting-Kim commented on src/main/java/com/depromeet/todolist/todo/dto/TodoResponse.java
> +        return new TodoResponse(todo.getContent(), todo.getType());
아 해당 클래스에서..! 여러 이름이 생겨날 것 같지 않다.. 맞네요..!!!

2022-04-07 14:14 UTC, Ting-Kim commented on src/main/java/com/depromeet/todolist/common/dto/ApiResult.java
> +    private final ApiError error;
아 여기서부터 hidden wrapping 처리되서 확인을 못했었네요 ㅋㅋㅋ

음 성공했을 때는 빈값이 들어가고 실패했을 때는 값이 들어가게끔 다소 일차원적으로 생각했어요.
특정 프로퍼티 값에 따라 response 형태를 달리 할 수 있는 방법이 있을까요?

2022-04-07 14:16 UTC, Ting-Kim commented on src/main/java/com/depromeet/todolist/common/dto/ApiResult.java
> +    }
각 api 마다 응답 데이터를 wrapping 해주기 위해서 사용했습니다.
List<TodoResponse> 가 들어갈 수 있고, TodoResponse 단일 값이 들어갈 수 있고
다른 도메인에서나 복합적인 도메인이 섞인 응답값 등에서도 범용적으로 사용할 수 있을 것 같아서요..!

2022-04-07 14:17 UTC, Ting-Kim commented on src/main/java/com/depromeet/todolist/todo/dto/TodoRequest.java
> +    }
오호 알아보겠습니다!

2022-04-07 14:24 UTC, Ting-Kim commented on src/main/java/com/depromeet/todolist/todo/Todo.java
> +    }
요것도 정적 팩토리 메서드를 사용하는게 좋지 않을까 생각했는데, 정적 팩토리 메서드를 사용하면 좋은 케이스에 대해서 학습할 필요가 있겠네요🥲

2022-04-07 14:28 UTC, Ting-Kim commented on src/main/java/com/depromeet/todolist/todo/TodoController.java
> +    }
아 이 부분도 궁금했는데요.

롬복에서 생성자 어노테이션을 사용할 경우고 만약 TodoService 와 여러 Impl 버전이 존재한다고 했을 때,
TodoService 프로퍼티에 특정 구현체를 주입시키고 싶다면 어떻게 사용해야 할까요?

저는 아래와 같이 사용해야 하지 않을까 라고 생각했었거든요. 인사이트를 공유해주세요 :)

``` java
  // TodoServiceFirstImpl 주입을 원함
  private final TodoService todoService;

  public TodoController(TodoServiceFirstImpl todoService) {
        this.todoService = todoService;
    }
```

2022-04-07 14:30 UTC, Ting-Kim commented on src/main/java/com/depromeet/todolist/todo/TodoService.java
> +    public Optional<List<TodoResponse>> findAll() {
오 이 부분 고민되었는데 감사합니다.
저번에 Controller로 넘길 때 Wrapping 해주는 것이 좋다고 말씀하신게 기억나서 이렇게 해봤는데, Optional이 아닌 객체로 Wrapping 하고 그걸 response 까지 사용하는 형태가 좋을까요?

2022-04-07 14:40 UTC, Ting-Kim commented on src/main/java/com/depromeet/todolist/todo/TodoService.java
> +        findById(todoId).update(todoRequest);
좋은 포인트 이십니다 🙌🏻

2022-04-07 14:42 UTC, Ting-Kim commented on src/main/java/com/depromeet/todolist/todo/TodoController.java
> +                        .orElseThrow(() -> new IllegalArgumentException()));
아, 이 리뷰 이전까지가 `hidden wrapping conversation` 에 해당되서 착각했네요 ㅋㅋㅋ이해했습니다!!

2022-04-07 16:13 UTC, Hyung1Jung commented on src/main/java/com/depromeet/todolist/todo/dto/TodoResponseDto.java
> +@Data
안녕하세요! 지나가는 나그네입니다.

- https://cheese10yun.github.io/lombok/
- https://velog.io/@rosa/Lombok-%EC%A7%80%EC%96%91%ED%95%B4%EC%95%BC-%ED%95%A0-annotation

짧고 부족한 의견이지만, 혹시나 도움이 되시지 않을까 해서 링크 두 개 걸어보겠습니다~

2022-04-07 16:15 UTC, Hyung1Jung commented on src/main/java/com/depromeet/todolist/todo/Todo.java
> +import javax.persistence.*;
`*`로 인해 모든 어노테이션이 import는 문제가 생겨, 풀어서 사용하면 메모리 최적화 하는데 아~주 조금이나마 도움이 되지 않을까 싶어서 리뷰 남겨봅니다!

2022-04-07 16:25 UTC, Ting-Kim commented on src/main/java/com/depromeet/todolist/todo/Todo.java
> +import javax.persistence.*;
오.. 전혀 생각지 못한 부분이네요! 
왜 저렇게 걸려있나 보니까 인텔리제이에서 5개 임포트 한 순간부터 `*` 로 자동으로 수정되네요.
이 부분도 한번 찾아봐야겠어요!!

2022-04-07 16:29 UTC, Hyung1Jung commented on src/main/java/com/depromeet/todolist/todo/dto/TodoResponseDto.java
> +@Data
감사합니다!

2022-04-07 16:53 UTC, Hyung1Jung commented on src/main/java/com/depromeet/todolist/common/dto/ApiError.java
> +    }
답은 아니지만, header code가 담겨있다면 response body에 code를 포함하는 건 리소스 낭비일 수도 있겠다는 생각이 듭니다!

2022-04-08 11:11 UTC, DongGeon0908 commented on src/main/java/com/depromeet/todolist/common/dto/ApiResult.java
> +    private final ApiError error;
성공과 실패 로직이 분리되는 건 어떨까요?

2022-04-08 11:17 UTC, DongGeon0908 reviewed
고생하셨습니당~

2022-04-08 11:17 UTC, DongGeon0908 commented on src/main/java/com/depromeet/todolist/common/dto/ApiResult.java
> +    }
현재는 쓰이지 않는 것 같아서 여쭤봤습니다!

2022-04-08 11:17 UTC, DongGeon0908 commented on src/main/java/com/depromeet/todolist/todo/Todo.java
> +    }
말씀하신 의도로 접근제한자를 사용했다면, 모든 클래스에서 접근제한자를 바탕으로 제한을 두는 코드로 작성해야 될 것 같아용

2022-04-08 11:17 UTC, DongGeon0908 commented on src/main/java/com/depromeet/todolist/todo/TodoController.java
> +    }
이렇게 구현해도 되고, 아에 앞단에서 어떤 bean을 주입할지 설정해줘도 좋을 것 같아요!

2022-04-08 11:17 UTC, DongGeon0908 commented on src/main/java/com/depromeet/todolist/todo/TodoController.java
> +    }
bean을 설정하는 부분에 대해 찾아보시면 도움이 될 것 같습니다! (토비의 스프링 굳굳!!)

2022-04-08 11:17 UTC, DongGeon0908 commented on src/main/java/com/depromeet/todolist/todo/TodoService.java
> +    public Optional<List<TodoResponse>> findAll() {
넵넵 맞아요!!

2022-04-08 11:17 UTC, DongGeon0908 commented on src/main/java/com/depromeet/todolist/todo/TodoService.java
> +        return Optional.of(todoResponses);
넵넵 맞습니다!!

2022-04-08 11:17 UTC, DongGeon0908 commented on src/main/java/com/depromeet/todolist/todo/TodoService.java
> +        return Optional.of(todoResponses);
넷플릭스에서 자체적으로 만든 코드 규약이 있는데, 해당 부분에 대해 자세히 설명하고 있어요!
참고하시면 좋을 것 같아용

2022-04-08 11:17 UTC, DongGeon0908 commented on src/main/java/com/depromeet/todolist/todo/TodoService.java
> +    // COMMENT: @Transactional(readOnly = true)를 생략해도 되는지
자세히 이해가 되지 않긴 하지만, 만약에 다른 트랜잭션이 묶여있다면, 부모 트랜잭션이 필요합니다!
해당 내용은 트랜잭션의 전파에 대한 것 같네요!!

2022-04-08 11:17 UTC, DongGeon0908 commented on src/main/java/com/depromeet/todolist/todo/TodoService.java
> +    // COMMENT: @Transactional(readOnly = true)를 생략해도 되는지
코드로 설명해주실 수 있으실까요?

2022-09-26 14:22 UTC, merged