Dev/sieun kiim [todoList - 1] todo - list 기능 구현
depromeet/todo-list-study pull request #6
Opened 2022-10-03 05:28 UTC by SieunKiim

사용자별 todoList 구현

**구현한 기능**
- 사용자 (추가/ 조회/ 삭제)
- todo (추가/ 단일조회/ 전체조회/ 수정/ 삭제)

2022-10-03 05:52 UTC, DongGeon0908 requested changes
학습하실때 도움되는 키워드를 리뷰에 작성했습니다!
파이팅~

2022-10-03 05:52 UTC, DongGeon0908 commented on README.md
> -> Made By 극락코딩, 궁금하신 내용이 있다면 언제든 연락주세요!!
README에 본인이 어떤 구조로 코드를 작성했는지 작성해주세요

2022-10-03 05:52 UTC, DongGeon0908 commented on src/main/java/com/depromeet/todolist/controller/TodoListController.java
> +@RequestMapping("/user")
Rest API의 Path는 보통 어떤 구조를 가져갈까요?

2022-10-03 05:52 UTC, DongGeon0908 commented on src/main/java/com/depromeet/todolist/controller/TodoListController.java
> +    public List<ResponseTodoDto> userTodoList(@PathVariable Long id) { // 전체 투두 목록 조회
ResponseEntity에 대해 알아보시길 추천드립니다.

2022-10-03 05:52 UTC, DongGeon0908 commented on src/main/java/com/depromeet/todolist/controller/TodoListController.java
> +        log.info("userTodoList 목록 조회");
log를 찍을 이유가 있나요??

2022-10-03 05:52 UTC, DongGeon0908 commented on src/main/java/com/depromeet/todolist/controller/TodoListController.java
> +    @ResponseStatus(HttpStatus.CREATED)
content가 없는건 204아닌가요?

2022-10-03 05:52 UTC, DongGeon0908 commented on src/main/java/com/depromeet/todolist/controller/TodoListController.java
> +    @PostMapping("/{id}")
반환값이 없는 구조인데, 이유가 있을까요?

2022-10-03 05:52 UTC, DongGeon0908 commented on src/main/java/com/depromeet/todolist/controller/UserController.java
> +    @PostMapping("")
```suggestion
    @PostMapping
```

2022-10-03 05:52 UTC, DongGeon0908 commented on src/main/java/com/depromeet/todolist/controller/UserController.java
> +    //유저 삭제
불필요한 주석 같네요! 위도 마찬가지구요

2022-10-03 05:52 UTC, DongGeon0908 commented on src/main/java/com/depromeet/todolist/controller/UserController.java
> +public class UserController {
상태코드를 맞춰주는 것도 중요합니다!

2022-10-03 05:52 UTC, DongGeon0908 commented on src/main/java/com/depromeet/todolist/controller/UserController.java
> +@RequestMapping("/")
path 형식을 수정해주세요

2022-10-03 05:52 UTC, DongGeon0908 commented on src/main/java/com/depromeet/todolist/dto/request/RequestTodoDto.java
> +
title에 Long type이 들어오면 어떻게 될까요?

2022-10-03 05:52 UTC, DongGeon0908 commented on src/main/java/com/depromeet/todolist/dto/request/RequestUserDto.java
> +}
무분별한 롬복 사용 지양

2022-10-03 05:52 UTC, DongGeon0908 commented on src/main/java/com/depromeet/todolist/dto/response/ResponseUserDto.java
> +@Data
response를 final하게 가져가도 되지 않을까요?

2022-10-03 05:52 UTC, DongGeon0908 commented on src/main/java/com/depromeet/todolist/entity/Todo.java
> +@AllArgsConstructor
무분별한 롬복 사용 지양

2022-10-03 05:52 UTC, DongGeon0908 commented on src/main/java/com/depromeet/todolist/entity/Todo.java
> +    @GeneratedValue(strategy = GenerationType.IDENTITY)
id 생성 전략에 대해 알려주실 수 있으실까요?

2022-10-03 05:52 UTC, DongGeon0908 commented on src/main/java/com/depromeet/todolist/entity/Todo.java
> +    @JoinColumn(name = "userid", nullable = false)
db 표기법은 스네이크 표기법입니다.

2022-10-03 05:52 UTC, DongGeon0908 commented on src/main/java/com/depromeet/todolist/entity/User.java
> +    private List<Todo> todoList = new ArrayList<>();
일급 컬렉션을 사용하는 건 어떨까요?

2022-10-03 05:52 UTC, DongGeon0908 commented on src/main/java/com/depromeet/todolist/entity/User.java
> +@AllArgsConstructor
무분별한 롬복 사용을 지양!

2022-10-03 05:52 UTC, DongGeon0908 commented on src/main/java/com/depromeet/todolist/service/TodoService.java
> +            return new ArrayList<>();
user가 없는 건 error 상황인데요, 이럴때 throw로 던져주는 건 어떨까요?
추가적으로 ControllerAdvice에 대해 학습해보시길

2022-10-03 05:52 UTC, DongGeon0908 commented on src/main/java/com/depromeet/todolist/service/TodoService.java
> +            return responseTodoDtoList;
간결하게 줄일 수 있을 것 같네요

2022-10-03 05:52 UTC, DongGeon0908 commented on src/main/java/com/depromeet/todolist/service/TodoService.java
> +        Todo todo = todoRepository.findById(todoId).orElse(null);
null을 뱉는게 맞을까요?
exception 터트려주소, controlleradvice로 handle해주는게 좋을 듯 하네요

2022-10-03 05:52 UTC, DongGeon0908 commented on src/main/java/com/depromeet/todolist/service/TodoService.java
> +        }
setter를 쓰지 않았으면 합니다.
불필요한 로그를 생략해주세요

2022-10-03 05:52 UTC, DongGeon0908 commented on src/main/java/com/depromeet/todolist/service/TodoService.java
> +    }
음 결국에 모든 코드에서 exception 처리를 if-else로 하신 것 같은데요
아마도 ControllerAdvice와 ErrorHandler, Exception에 대한 학습이 부족하셨던 것 같습니다!
해당 키워드를 기반으로 학습을 진행하시고 리펙토링 진행해주세용~

2022-10-03 05:52 UTC, DongGeon0908 commented on src/main/java/com/depromeet/todolist/service/UserService.java
> +}
eof 설정 및 코드 리펙토링 부탁드려요!!
불필요한 주석 삭제 부탁드립니다

2022-10-03 10:56 UTC, SieunKiim commented on src/main/java/com/depromeet/todolist/controller/TodoListController.java
> +@RequestMapping("/user")
Rest 규칙중에 
- "URL에 작성되는 영어를 복수형으로 사용한다"

가 있었군용

2022-10-04 07:04 UTC, SieunKiim commented on src/main/java/com/depromeet/todolist/controller/TodoListController.java
> +        log.info("userTodoList 목록 조회");
실행했을 때 동작하는지 어디서 동작하는지 보려고 log 사용했었습니다..!

2022-10-04 07:12 UTC, SieunKiim commented on src/main/java/com/depromeet/todolist/dto/response/ResponseUserDto.java
> +@Data
response는 반환 시 생성 이후 변동 할 일이 없기 때문에 안정성을 위해서 final 선언을 하는게 맞을까요?

2022-10-04 07:26 UTC, SieunKiim commented on src/main/java/com/depromeet/todolist/service/TodoService.java
> +            return responseTodoDtoList;
Stream을 활용하는 방법이 맞을까요??

2022-10-04 07:28 UTC, SieunKiim commented on src/main/java/com/depromeet/todolist/service/TodoService.java
> +        Todo todo = todoRepository.findById(todoId).orElse(null);
null 반환시 controller에서 UserNotFoundExcption 발생하도록 수정했습니다

2022-10-04 07:57 UTC, SieunKiim commented on src/main/java/com/depromeet/todolist/entity/Todo.java
> +    @GeneratedValue(strategy = GenerationType.IDENTITY)
사용자 이름을 (@Id)로 해서, 생성 시 중복된 아이디 확인 후, 중복되는 아이디가 없으면 추가 하는 방향으로 수정 및 간소화 하였습니다.

2022-10-04 08:34 UTC, SieunKiim commented on src/main/java/com/depromeet/todolist/service/TodoService.java
> +        }
JPA의 entity 변경 감지 부분을 더 학습해보겠습니다!

2022-10-04 08:36 UTC, SieunKiim commented on src/main/java/com/depromeet/todolist/dto/request/RequestTodoDto.java
> +
무분별한 lombok 사용과 관계되는 내용이 맞을까요? 😂 관련 부분 수정했습니다!

2022-10-04 09:02 UTC, SieunKiim commented on src/main/java/com/depromeet/todolist/service/UserService.java
> +}
eof 설정은 어떤건가요...? 🥹

2022-10-12 13:07 UTC, DongGeon0908 requested changes
리뷰 드렸습니다!

2022-10-12 13:07 UTC, DongGeon0908 commented on src/main/java/com/depromeet/todolist/exception/CustomExceptionHandler.java
> +@ControllerAdvice
@RestControllerAdvice

2022-10-12 13:07 UTC, DongGeon0908 commented on src/main/java/com/depromeet/todolist/exception/customException/DuplicatedUserException.java
> +public class DuplicatedUserException extends RuntimeException {
RuntimeException을 상속한 Exception 클래스를 만들고, 해당 클래스를 Exception해서 상세 Exception을 만드는 건 어떨까요?
보통 BusinessException이라는 명칭을 많이 사용해요

2022-10-12 13:07 UTC, DongGeon0908 commented on src/main/java/com/depromeet/todolist/entity/User.java
> +    }
@Noargs.. 롬복!

2022-10-12 13:07 UTC, DongGeon0908 commented on src/main/java/com/depromeet/todolist/service/TodoService.java
> +            todoRepository.delete(todo);
deleteById도 있어요

2022-10-12 13:07 UTC, DongGeon0908 commented on src/main/java/com/depromeet/todolist/service/TodoService.java
> +    }
Todo가 없으면 exception을 던지는 건 어떨까요?

2022-10-12 13:07 UTC, DongGeon0908 commented on src/main/java/com/depromeet/todolist/controller/UserController.java
> +public class UserController {
Swagger를 통한 문서화를 진행해보시죠

2022-10-12 13:07 UTC, DongGeon0908 commented on src/main/java/com/depromeet/todolist/controller/UserController.java
> +@RequestMapping("/users")
/api/users/v1 이런 구조1

2022-10-12 13:07 UTC, DongGeon0908 commented on src/main/java/com/depromeet/todolist/controller/UserController.java
> +        }
여기서 던지는게 맞을까요?

2022-10-12 13:07 UTC, DongGeon0908 commented on src/main/java/com/depromeet/todolist/controller/UserController.java
> +        User user = userService.findUser(requestUserDto);
Entity가 Controller까지 나와야 할가요??

2022-10-12 13:07 UTC, DongGeon0908 commented on src/main/java/com/depromeet/todolist/controller/UserController.java
> +        RequestUserDto requestUserDto = new RequestUserDto(name);
래핑을 하는 이유가 궁금해요

2022-10-12 13:07 UTC, DongGeon0908 commented on src/main/java/com/depromeet/todolist/controller/TodoListController.java
> +        if (user == null) throw new UserNotFoundException();
여기서 던지는게 맞을까용

2022-10-12 13:07 UTC, DongGeon0908 commented on src/main/java/com/depromeet/todolist/controller/TodoListController.java
> +        return new ResponseEntity<>(new ResponseTodoDto(updatedTodo.getId(), updatedTodo.getTitle()), HttpStatus.CREATED);
여기서 조립할 필요가 있을까요??

2022-10-12 13:07 UTC, DongGeon0908 commented on src/main/java/com/depromeet/todolist/controller/TodoListController.java
> +        }
로직이 복잡하다 -> 잘못되었다 혹은 고쳐야 한다
다른 사람이 읽기 쉬운 코드가 좋은 코드입니다!

2022-10-12 13:07 UTC, DongGeon0908 commented on src/main/java/com/depromeet/todolist/controller/TodoListController.java
> +@RequestMapping("/users/{name}/todo-list")
rest-api 규칙을 한번 찾아보시죠!

2022-10-12 13:07 UTC, DongGeon0908 commented on src/main/java/com/depromeet/todolist/controller/TodoListController.java
> +@Transactional
트랜잭션이????????

2022-10-12 18:29 UTC, minsoozz commented
@SieunKiim 열심히 하시는 모습 본받으러 왔습니다!!

2022-10-13 11:19 UTC, SieunKiim commented on src/main/java/com/depromeet/todolist/entity/User.java
> +    }
쿨럭...!

2022-10-13 11:20 UTC, SieunKiim commented on src/main/java/com/depromeet/todolist/controller/UserController.java
> +        RequestUserDto requestUserDto = new RequestUserDto(name);
컨트롤러에서는 Dto로 다룬다는 점에 너무 과몰입했나봐요..! 수정했습니다!

2022-10-13 13:21 UTC, SieunKiim commented
- 복잡한 로직을 세분화 하여 하나의 메서드가 하나의 기능을 수행할 수 있도록 나눴습니다!
- Controller 에서는 Dto를 다루고, Service에서는 엔티티를 다룰 수 있도록 수정했습니다.
    - Service 에서 Controller 로 값을 전달할 때 Dto로 변환하여 넘겨주도록 entityToDto 메서드를 추가했습니다.
- BusinessException과 ErrorCode를 통해 중복을 피하고 다양한 예외 처리를 할 수 있도록 수정했습니다.
- Swagger 문서화
![image](https://user-images.githubusercontent.com/39111133/195606424-c300a039-fa5d-4088-b50d-a492ae620f1f.png)

2022-10-14 12:15 UTC, DongGeon0908 requested changes
고생하셨습니다
다음 단계는 다른 사람이 보기에 읽기 쉬운 코드로 리펙토링 해보시죠!

2022-10-14 12:15 UTC, DongGeon0908 commented on src/main/java/com/depromeet/todolist/entity/User.java
> +@NoArgsConstructor
기본 생성자를 외부에서 접근할 수 없게 막는 방법은 무엇이 있을까요?

2022-10-14 12:15 UTC, DongGeon0908 commented on src/main/java/com/depromeet/todolist/service/UserService.java
> +        return userEntityToDto(savedUser);
읽기 어렵네요
문단을 조금 나눠보는 건 어떨까요?

2022-10-15 03:32 UTC, SieunKiim commented on src/main/java/com/depromeet/todolist/entity/User.java
> +@NoArgsConstructor
AccessLevel에 대해서 정리해보겠습니다!!

2022-10-19 05:57 UTC, DongGeon0908 reviewed
몇가지 안내를 드렸어요 확인하시고 수정해주세요

2022-10-19 05:57 UTC, DongGeon0908 commented on src/main/java/com/depromeet/todolist/entity/User.java
> +    private String name;
동명의 이름을 가진 사람이 있으면 해당 로직은 빵꾸 아닐까요?

2022-10-19 05:57 UTC, DongGeon0908 commented on src/main/java/com/depromeet/todolist/repository/TodoRepository.java
> +    List<Todo> findAllTodos(@Param("username") String username);
쿼리로 할 필요가 있나요??

2022-10-25 07:34 UTC, SieunKiim commented on src/main/java/com/depromeet/todolist/entity/User.java
> +    private String name;
UserService.class 의 `createUser`에서 사용자를 생성할 때 `checkUserDuplicated`를 활용해 같은 이름으로 저장된 사용자가 있는지 확인하는 방식으로 구현했습니다! 혹시 다른 방법이 있을까요?

2022-10-25 07:35 UTC, SieunKiim commented on src/main/java/com/depromeet/todolist/repository/TodoRepository.java
> +    List<Todo> findAllTodos(@Param("username") String username);
😀 수정해보겠습니다!

2022-10-25 07:45 UTC, minsoozz commented on src/main/java/com/depromeet/todolist/entity/User.java
> +    private String name;
안녕하세요. 말씀하신 것처럼 `checkUserDuplicated`을 활용해 같은 이름으로 저장된 사용자가 있는지 확인하는 방법이 있지만,
애플리케이션의 관점이 아닌 데이터베이스 관점에서 바라보는 것은 어떠실까요?
기본 키 전략은 비즈니스적으로 의미가 없는 대체 키로 구성하는 것이 좋습니다. 비즈니스 요구사항이 변경된다면 그것에 맞게 작업이 필요할뿐더러 여러 가지 단점이 존재합니다. 제 설명이 부족할 수 있으니 하단에 링크 첨부해드리겠습니다 😊

https://jojoldu.tistory.com/672

2022-10-25 07:47 UTC, SieunKiim commented on src/main/java/com/depromeet/todolist/entity/User.java
> +    private String name;
도움주셔서 감사합니다!! 참고해서 수정해볼게요!! 🫡

2022-10-26 15:30 UTC, SieunKiim commented
사용자 이름을 User엔티티의 @Id로 했어서 동명이인에 대한 문제를 고려하지 못했었습니다!

2022-10-29 15:07 UTC, DongGeon0908 reviewed
1. swagger 적용 부탁드립니다
2. 이전에 리뷰드린 내용에 대해 수정 작업 부탁드립니다
3. spirng validate를 사용해보는 건 어떨까요?>

2022-10-29 15:07 UTC, DongGeon0908 commented on src/main/java/com/depromeet/todolist/controller/TodoListController.java
> +        List<ResponseTodoDto> userTodoList = todoService.getUserTodoList(userId);
```suggestion
        List<ResponseTodoDto> response = todoService.getUserTodoList(userId);
```
list를 변수명으로 사용하는건 좋지 않아요
자료구조명칭을 네이밍으로 사용하지 않거든요

2022-10-29 15:07 UTC, DongGeon0908 commented on src/main/java/com/depromeet/todolist/controller/TodoListController.java
> +        ResponseTodoDto responseTodoDto = todoService.getTodo(userId, todoId);
dto가 request인지 response 용인지 알 수 있는 네이밍이면 어떨까요?

2022-10-29 15:07 UTC, DongGeon0908 commented on src/main/java/com/depromeet/todolist/controller/TodoListController.java
> +        return ResponseEntity.created(URI.create("/api/v1/users/"+ userId +"/todos")).body(responseTodoDto);
음 Hateoas를 적용하는 건 어떨까요?

2022-10-29 15:07 UTC, DongGeon0908 commented on src/main/java/com/depromeet/todolist/service/TodoService.java
> +        return todoEntityToDto(todo);
팩토리 메서드라는게 있는데 한번 보시길 추천드립니다

2022-11-01 11:39 UTC, SieunKiim commented
> 1. swagger 적용 부탁드립니다
> 2. 이전에 리뷰드린 내용에 대해 수정 작업 부탁드립니다
> 3. spirng validate를 사용해보는 건 어떨까요?

주신 의견 중, 2번에서 혹시 리뷰해주신 내용 중 제가 반영하지 못한 부분이 어떤건지 알 수 있을까요? 🥹

2022-11-01 13:19 UTC, DongGeon0908 requested changes
몇가지 추가 개선사항 전달드립니다.
1. Swagger를 통한 문서화 진행
2. 읽기 쉬운 코드, 간결한 코드로 수정

위의 2가지만 수정해주세요

2022-11-01 13:19 UTC, DongGeon0908 commented on src/main/java/com/depromeet/todolist/service/CommonService.java
> +}
이거 UserService아닌가요?

2022-11-02 14:37 UTC, SieunKiim commented
## 구현 및 수정 내용

- Dto 클래스 내 각각 Response와 Request 스태틱 클래스를 구현
- Hateos 적용
- 자료구조명이 포함된 변수명 수정
- Entity와 Dto 변환을 Service가 아닌 Converter로 분리하였습니다.

---
## 예정

- Spring valid 적용
- 펙토리 메서드 적용
- Spring security 활용한 회원가입 및 로그인

위 내용 시도해볼까 합니다!! 😀

2023-10-30 17:20 UTC, closed without merging