Dev/be student TodoList 1차
depromeet/todo-list-study pull request #7
Opened 2022-10-05 18:12 UTC by be-student

JPA로 작성했고, 정말 간단한 crud를 제작했습니다

2022-10-06 12:48 UTC, DongGeon0908 requested changes
안녕하세요!! 고생하셨습니다!!
몇가지 안내를 드릴게요!!

1. README 작성하기
2. HttpStatus, ResponseEntity 찾아보기
3. Error가 발생하면 Handling을 어떻게 할까???
4. SpringBoot-JPA로 바꿔보기!

2022-10-06 12:48 UTC, DongGeon0908 commented on src/main/java/com/depromeet/todolist/adaptor/HealthController.java
> -package com.depromeet.todolist.common;
README 작성 부탁드립니다!

2022-10-06 12:48 UTC, DongGeon0908 commented on src/main/java/com/depromeet/todolist/infrastructure/mysql/TodoJpaRepository.java
> +package com.depromeet.todolist.infrastructure.mysql;
패키지 구조를 이렇게 설계하신 이유가 궁금합니다!

2022-10-06 12:48 UTC, DongGeon0908 commented on src/main/java/com/depromeet/todolist/application/TodoService.java
> +    }
String으로 내보내는 이유가 있을까요??
그리고 Entity를 바로 내보내야 할까요?

2022-10-06 12:48 UTC, DongGeon0908 commented on src/main/java/com/depromeet/todolist/application/TodoService.java
> +    }
id값으로 조회를 했는데, 데이터가 없으면 어떤 일이 발생할까요?

2022-10-06 12:48 UTC, DongGeon0908 commented on src/main/java/com/depromeet/todolist/application/TodoService.java
> +        return this.todoRepository.delete(id);
보통 this를 여기서 쓰지는 않아요

2022-10-06 12:48 UTC, DongGeon0908 commented on src/main/java/com/depromeet/todolist/infrastructure/mysql/TodoJpaRepository.java
> +    }
롬복을 사용하신 곳이 있고, 아닌 곳이 있네요
컨벤션 통일은 중요합니다!

2022-10-06 12:48 UTC, DongGeon0908 commented on src/main/java/com/depromeet/todolist/infrastructure/mysql/TodoJpaRepository.java
> +    }
페이지로 처리하는 건 어떨까요?
만약에 데이터가 10만건이면?

2022-10-06 12:48 UTC, DongGeon0908 commented on src/main/java/com/depromeet/todolist/infrastructure/mysql/TodoJpaRepository.java
> +public class TodoJpaRepository implements ITodoRepository {
I를 붙인 이유가 궁금합니다

2022-10-06 12:48 UTC, DongGeon0908 commented on src/main/java/com/depromeet/todolist/infrastructure/mysql/TodoEntity.java
> +public class TodoEntity extends BaseEntity implements ITodoItem {
ITodoItem이 왜 필요할까요

2022-10-06 12:48 UTC, DongGeon0908 commented on src/main/java/com/depromeet/todolist/infrastructure/mysql/TodoEntity.java
> +@NoArgsConstructor
롬복을 사용하는 건 좋은데, 무분별하게 난발하면 위험!!
롬복이 어떻게 동작하는지 확인하고 사용하시길!

2022-10-06 12:48 UTC, DongGeon0908 commented on src/main/java/com/depromeet/todolist/infrastructure/mysql/TodoEntity.java
> +    }
@Getter

2022-10-06 12:48 UTC, DongGeon0908 commented on src/main/java/com/depromeet/todolist/infrastructure/mysql/TodoEntity.java
> +    @GeneratedValue(strategy = GenerationType.IDENTITY)
ID 생성 전략에 대해 아실까요?

2022-10-06 12:48 UTC, DongGeon0908 commented on src/main/java/com/depromeet/todolist/domain/interfaces/ITodoItem.java
> +public interface ITodoItem {
해당 인터페이스를 만든 이유가 있을까요?

2022-10-06 12:48 UTC, DongGeon0908 commented on src/main/java/com/depromeet/todolist/adaptor/TodoController.java
> +@Controller
@RestController

2022-10-06 12:48 UTC, DongGeon0908 commented on src/main/java/com/depromeet/todolist/adaptor/TodoController.java
> +    public String createPost(@RequestParam String title,@RequestParam String content){
생성했을 때 보통 어떤 상태코드를 쓸까요??

2022-10-06 12:48 UTC, DongGeon0908 commented on src/main/java/com/depromeet/todolist/adaptor/TodoController.java
> +    public int deletePost(@PathVariable("id") String id){
PathVariable Long id

2022-10-06 12:48 UTC, DongGeon0908 commented on src/main/java/com/depromeet/todolist/adaptor/TodoController.java
> +        return post.toString();
여기서 Entity를 조립하는 것보다는 service로 던지는 건 어떨까요?

2022-10-06 12:48 UTC, DongGeon0908 commented on src/main/java/com/depromeet/todolist/adaptor/TodoController.java
> +@Controller
HttpStatus에 대해 조사해보시길!

2022-10-12 18:22 UTC, be-student commented on src/main/java/com/depromeet/todolist/adaptor/HealthController.java
> -package com.depromeet.todolist.common;
코드리뷰를 받으면 최대한 빠르게 comment를 달아야 한다는 것을 잘 몰랐어서 지금이라도 다 달도록 하겠습니다.
늦어서 죄송합니다.

네 작성하겠습니다

2022-10-12 18:29 UTC, minsoozz commented
은우님 화이팅!!!

2022-10-12 18:31 UTC, be-student commented on src/main/java/com/depromeet/todolist/infrastructure/mysql/TodoJpaRepository.java
> +package com.depromeet.todolist.infrastructure.mysql;
의존성을 최대한 원하는 방향으로 흘러가도록 만들어 가보고 싶었는데요
domain<-application<-adaptor<-infrastructure
순으로만 참조가 일어나도록 만들어보고 싶어서 이렇게 만들게 되었습니다.
이때 정확하게 interface로 주입하는 과정을 몰라서 정확하게 못했던 것 같아요

2022-10-12 18:32 UTC, be-student commented on src/main/java/com/depromeet/todolist/application/TodoService.java
> +    }
String으로 내보내는 이유는 일단 json으로 내보내는 방법을 몰라서 작성했고요
Entity대신, Record타입이라는 것을 몰랐을 때라서, record타입으로 변경해서 작성하도록 해보겠습니다

2022-10-12 18:35 UTC, be-student commented on src/main/java/com/depromeet/todolist/application/TodoService.java
> +    }
Optional에 대한 처리를 제대로 안 해서 아무것도 return되지 않고, 그냥 완벽한 에러페이지로 가버리네요

2022-10-12 18:37 UTC, be-student commented on src/main/java/com/depromeet/todolist/application/TodoService.java
> +        return this.todoRepository.delete(id);
다른 언어에서 쓰던 습관이 있어서 사용했던 것 같습니다
앞으로는 명시적으로 꼭 this를 사용하지 않아도 되는 경우에는 사용하지 않도록 하겠습니다

2022-10-12 18:37 UTC, be-student commented on src/main/java/com/depromeet/todolist/infrastructure/mysql/TodoJpaRepository.java
> +    }
앞으로는 @RequiredArgs 같은 것으로 통일하도록 하겠습니다

2022-10-12 18:38 UTC, be-student commented on src/main/java/com/depromeet/todolist/infrastructure/mysql/TodoJpaRepository.java
> +    }
훨씬 좋을 것 같네요 그렇게 수정하겠습니다

2022-10-12 18:38 UTC, be-student commented on src/main/java/com/depromeet/todolist/infrastructure/mysql/TodoJpaRepository.java
> +public class TodoJpaRepository implements ITodoRepository {
오늘 여쭤보니, I를 붙히는 것이 옛날에 Interface라는 것을 보여주기 위한 것이라고 해서, 앞으로는 그냥 작성하는 것으로 변경하도록 하겠습니다

2022-10-12 18:40 UTC, be-student commented on src/main/java/com/depromeet/todolist/infrastructure/mysql/TodoEntity.java
> +@NoArgsConstructor
커멘트를 보고 Lombok에 대해서 열심히 배웠습니다

2022-10-12 18:41 UTC, be-student commented on src/main/java/com/depromeet/todolist/infrastructure/mysql/TodoEntity.java
> +public class TodoEntity extends BaseEntity implements ITodoItem {
이 부분은 위에 있던 의존성의 방향을 고정해보기 위해서 이렇게 사용한 것이지 꼭 필요한 것은 아닐것이라고 생각합니다

그냥 패키지간의 양방향 의존성을 없애고 싶었습니다

2022-10-12 18:42 UTC, be-student commented on src/main/java/com/depromeet/todolist/infrastructure/mysql/TodoEntity.java
> +    }
넵 수정해서 진행하겠습니다

2022-10-12 18:42 UTC, be-student commented on src/main/java/com/depromeet/todolist/infrastructure/mysql/TodoEntity.java
> +    @GeneratedValue(strategy = GenerationType.IDENTITY)
GenerationType.IDENTITY같은 경우에는 db에 생성을 위임하도록 하는 것이라고 알고 있습니다

2022-10-12 18:42 UTC, be-student commented on src/main/java/com/depromeet/todolist/domain/interfaces/ITodoItem.java
> +public interface ITodoItem {
이 부분은 위에 있던 의존성의 방향을 고정해보기 위해서 이렇게 사용한 것이지 꼭 필요한 것은 아닐것이라고 생각합니다

그냥 패키지간의 양방향 의존성을 없애고 싶었습니다

2022-10-12 18:43 UTC, be-student commented on src/main/java/com/depromeet/todolist/adaptor/TodoController.java
> +@Controller
@RestController로 변경하겠습니다
응답할 때, 응답할 때 HttpStatus 를 수정하도록 하겠습니다

2022-10-12 18:44 UTC, be-student commented on src/main/java/com/depromeet/todolist/adaptor/TodoController.java
> +    public String createPost(@RequestParam String title,@RequestParam String content){
생성했을 때는 201번으로 사용했습니다

2022-10-12 18:44 UTC, be-student commented on src/main/java/com/depromeet/todolist/adaptor/TodoController.java
> +    public int deletePost(@PathVariable("id") String id){
넵 이렇게 변경하겠습니다

2022-10-12 18:46 UTC, be-student commented on src/main/java/com/depromeet/todolist/adaptor/TodoController.java
> +        return post.toString();
확실히 그 쪽이 훨씬 더 깔끔하게 코드가 작성될 것 같습니다

처음에 만들고자 했던 의존성 방향을 생각했을 때 지금 코드는 좋은 방향은 아닌 것 같아요

2022-10-21 08:34 UTC, DongGeon0908 commented on src/main/java/com/depromeet/todolist/application/TodoService.java
> +    }
답변을 드린 줄 알았는데, 아니네요... ㅜㅜ
dto를 만드는 건 어떨까요?

2022-10-21 08:34 UTC, DongGeon0908 commented on src/main/java/com/depromeet/todolist/application/TodoService.java
> +    }
error를 어떻게 처리해야 될까요?

2022-10-21 08:36 UTC, DongGeon0908 commented on src/main/java/com/depromeet/todolist/infrastructure/mysql/TodoEntity.java
> +public class TodoEntity extends BaseEntity implements ITodoItem {
불필요한 의존성 제어는 코드를 해석하기 더 어렵게 합니다!
물론, 아키텍쳐에 대한 고민을 많이 하는 건 좋지만, 코드를 해석하기 어렵게 짠다면 무용지물이죠!!

좋은 코드는 상대방이 읽기 편해야 합니다!

2022-10-21 08:37 UTC, DongGeon0908 commented on src/main/java/com/depromeet/todolist/domain/interfaces/ITodoItem.java
> +public interface ITodoItem {
그냥이라는 키워드는 앞으로 금지!

그리고 양방향 의존성에서 발생하는 문제점에 대해서 알려주세요

2023-10-30 17:20 UTC, closed without merging